services:
  postgres:
    image: postgres:16
    container_name: urlshortener-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - urlshortener_network

volumes:
  pgdata:

networks:
  urlshortener_network:
