services:
  postgres:
    image: postgres:16
    container_name: urlshortener-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - urlshortener_net
    ports:
      - "5433:5432"

  urlshortener-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener-1
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - postgres
    networks:
      - urlshortener_net
    ports:
      - "8081:8080"

  urlshortener-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener-2
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - postgres
    networks:
      - urlshortener_net
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    container_name: urlshortener-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - urlshortener-1
      - urlshortener-2
    networks:
      - urlshortener_net

volumes:
  pgdata:

networks:
  urlshortener_net:
