spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/urlshortener
    username: url_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
